app:
  # URL pública de acceso
  baseUrl: https://backstage.lksnext.com

auth:
  environment: production
  providers:
    microsoft:
      production:
        clientId: 492a7069-d258-4626-82e2-b2c491e5373e
        clientSecret: e~18Q~liOV1IHVHEHGjhEnb8nAzYQLqT6h6XCaQY
        tenantId: b85a15eb-1d5f-449e-93d8-77a9cba50013
        domainHint: b85a15eb-1d5f-449e-93d8-77a9cba50013
        redirectUri: https://backstage.lksnext.com/api/auth/microsoft/handler/frame?env=production
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityProfileEmail

backend:
  # Mismo dominio si está tras el mismo ingress
  baseUrl: https://backstage.lksnext.com
  listen:
    host: 0.0.0.0
    port: 7007
  auth:
    keys:
      # Referencia a la variable de entorno para el secreto del backend
      - secret: ${BACKEND_SECRET}
  cors:
    # Asegurar CORS para el frontend
    origin: https://backstage.lksnext.com

techdocs:
  builder: "local"
  generator:
    runIn: "local"
  publisher:
    type: "local"

database:
  client: pg
  connection:
    host: ${POSTGRES_HOST}
    port: ${POSTGRES_PORT}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

identity:
  organization: lksnext
  type: guest

permission:
  enabled: true
  policy:
    "@backstage/plugin-permission-node":
      rules:
        - permission: catalog.entity.read
          allow: [ALL]

# --- Configuración de SINCRONIZACIÓN del Catálogo LDAP ---
catalog:
  rules:
    - allow:
        [
          Component,
          API,
          Group,
          User,
          Template,
          System,
          Domain,
          Resource,
          Location,
        ]
  locations:
    - type: url
      target: https://gitlab.devops.lksnext.com/qa/backstage-example/-/blob/main/examples/structure/lks-org.yaml
      rules: 
        - allow: [User, Group] 

# --- Integración con GitLab ---
integrations:
  gitlab:
    - host: gitlab.devops.lksnext.com
      apiBaseUrl: https://gitlab.devops.lksnext.com/api/v4
      # Referencia a la variable de entorno para el token
      token: ${GITLAB_TOKEN}
