apiVersion: v1
kind: Secret
metadata:
  name: my-backstage-secrets
  namespace: tools
type: Opaque
stringData:
  # PostgreSQL credentials (las que espera el chart de Bitnami)
  postgres-password: "hunter2" # Para el usuario admin 'postgres'
  password: "hunter2" # Para el usuario 'bn_backstage'
  user-password: "hunter2" # Alternativa para compatibilidad

  # Backstage configuration
  POSTGRES_HOST: "backstage-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "bn_backstage"
  POSTGRES_PASSWORD: "hunter2"

  # Otros secrets para Backstage
  BACKEND_SECRET: "backstage-secret-value"
  AUTH_GITHUB_CLIENT_ID: "" # Rellenar si usas GitHub auth
  AUTH_GITHUB_CLIENT_SECRET: "" # Rellenar si usas GitHub auth

  GITLAB_TOKEN: "glpat-NSg4xsSstyLFd53qg-1U" # Rellenar si usas GitLab auth

  LDAP_BIND_PASSWORD: usuario1*
